post http://localhost:3000/login
Content-Type: application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}

###
get http://localhost:3000/states
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA1NjU5MDg2fQ.3W7Q78coLYpHjMmQqCBN95zWe0Kvozz1oB6vfMX2taU

###
get http://localhost:3000/states/2
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA1NjU5MDg2fQ.3W7Q78coLYpHjMmQqCBN95zWe0Kvozz1oB6vfMX2taU

###
post http://localhost:3000/districts
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA1NjU5MDg2fQ.3W7Q78coLYpHjMmQqCBN95zWe0Kvozz1oB6vfMX2taU
Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

###
get http://localhost:3000/districts/2
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA1NjU5MDg2fQ.3W7Q78coLYpHjMmQqCBN95zWe0Kvozz1oB6vfMX2taU

###
delete http://localhost:3000/districts/3
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA1NjU5MDg2fQ.3W7Q78coLYpHjMmQqCBN95zWe0Kvozz1oB6vfMX2taU

###
put http://localhost:3000/districts/4
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA1NjU5MDg2fQ.3W7Q78coLYpHjMmQqCBN95zWe0Kvozz1oB6vfMX2taU
Content-Type: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

###
get http://localhost:3000/states/2/stats/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA1NjU5MDg2fQ.3W7Q78coLYpHjMmQqCBN95zWe0Kvozz1oB6vfMX2taU
